### ISSUE TITLE
DNS integration

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/clabernetes#157]
Not really an issue with Clabernetes itself, but it would be nice to document how a deployment on Kubernetes can be accessed using DNS names

Similar to how Containerlab modifies /etc/hosts for easy access, I imagine it may be possible to use the Kubernetes DNS service to resolve hostnames - but how would one do that?

**Comment by carlmontanari** [comment]
of course you can resolve things with in cluster dns just like anything else in a cluster. 

if you run the naming mode in `non-prefixed` you will need to deploy labs into dedicated namespaces if hostnames of nodes in those labs overlap. but, if you do this, within that namespace you can just ping `srl1` or whatever the node name is. if you run prefixed mode (default) and are in the namespace you can ping `mytopo-srl1` where "mytopo" is the name of the topology of course. this all works because we create a service named according to the naming mode for each nodes in the clab topo.

the nodes in clab use the hosts dns which is in turn using coredns in the cluster. so the short answer for all of this is just read [this](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) and everything works just like it says with the only real caveat being that when you resolve that address you are really resolving the launcher (via the svc pointing to the launcher) so if you ssh to that resolved address and have ssh enabled as a port that will "work" but if you tried to do netconf and that was not exposed (via the exposed ports config in clab/topo) then it would fail even if the device was listening on 830.

ima close because not an issue/bug/thing to do I guess, if you wanna chat more about it lets do it in a discussion, having those open doesn't freak out my ocd 😁 


for context/to illustrate:

```
❯ k get svc -o wide | grep srl3
test-topology-1-srl3      LoadBalancer   10.101.72.11     10.201.0.3    22:31218/TCP,23:30685/TCP,161:30894/UDP,57400:31268/TCP,21:30146/TCP,80:31269/TCP,443:32260/TCP,830:30540/TCP,5000:31371/TCP,5900:31916/TCP,6030:32651/TCP,9339:32562/TCP,9340:30719/TCP,9559:30830/TCP                   18m   clabernetes/app=clabernetes,clabernetes/name=test-topology-1-srl3,clabernetes/topologyNode=srl3,clabernetes/topologyOwner=test-topology-1
test-topology-1-srl3-vx   ClusterIP      10.101.144.183   <none>        14789/UDP,4799/TCP                                                                                                                                                                                                        18m   clabernetes/app=clabernetes,clabernetes/name=test-topology-1-srl3,clabernetes/topologyNode=srl3,clabernetes/topologyOwner=test-topology-1


A:srl3# ping test-topology-1-srl3
Using network instance mgmt
PING test-topology-1-srl3.clabernetes.svc.cluster.local (10.101.72.11) 56(84) bytes of data.
From test-topology-1-srl3.clabernetes.svc.cluster.local (10.101.72.11) icmp_seq=1 Destination Port Unreachable
From test-topology-1-srl3.clabernetes.svc.cluster.local (10.101.72.11) icmp_seq=2 Destination Port Unreachable
```
